import { Navbar } from "@/components/ui/navbar";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>OIjwearoij</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>
  );
}
